### ISSUE TITLE
Tests in Travis are failing and timing out

### ISSUE THREAD

**Issue by Aosanders** [canjs/can-ndjson-stream#36]
Travis will time out when running tests.
Have been doing so for the past 5 months.
https://travis-ci.org/canjs/can-ndjson-stream/branches

**Comment by phillipskevin** [comment]
I added debug info for testee on https://travis-ci.org/canjs/can-ndjson-stream/builds/399648939 and the error is:

```
Tue, 03 Jul 2018 16:05:23 GMT testee:runner [4480:4480:0703/160523.100990:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by phillipskevin** [comment]
There are a few threads about this
https://github.com/travis-ci/travis-ci/issues/8836
https://github.com/travis-ci/travis-ci/issues/9024
