### ISSUE TITLE
Example showing how to use this library with axios

### ISSUE THREAD

**Issue by kanteankit** [canjs/can-ndjson-stream#41]
Hi 
There is an example of how to use this library when fetching data using the `fetch` method. Can you guys add an example of how to use this library with [axios](https://github.com/axios/axios)?

**Comment by justinbmeyer** [comment]
I've never used axios.  Does axios support ReadableStream?  If not, it won't work with `can-ndjson-stream`.

Are you using axios for backwards compatibility?  Could you use `fetch` instead?  Thanks!

**Comment by kanteankit** [comment]
I guess people are demanding stream support for axios and there is no definitive support as of yet. 
Axios is gainining popularity and thought you might have an example for that. I'll use `fetch`.
Thanks for your help :)
